# Generated by Django 4.0.4 on 2022-06-13 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vox', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
