# Generated by Django 4.0.4 on 2022-06-14 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vox', '0002_post_post_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_img',
        ),
        migrations.AddField(
            model_name='post',
            name='postimg',
            field=models.ImageField(blank=True, null=True, upload_to='static/images'),
        ),
        migrations.AlterField(
            model_name='post',
            name='caption',
            field=models.ImageField(upload_to=None, verbose_name=''),
        ),
    ]
