# Generated by Django 4.0.4 on 2022-06-14 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vox', '0004_remove_post_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postimg',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
