# Generated by Django 4.0.4 on 2022-07-24 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vox', '0007_post_likes_alter_post_date_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.DeleteModel(
            name='like',
        ),
    ]
