# Generated by Django 4.0.4 on 2022-07-25 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vox', '0011_alter_profile_bio_alter_profile_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Bio',
            new_name='bio',
        ),
    ]
