# Generated by Django 4.0.4 on 2022-08-10 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vox', '0015_remove_comment_post_post_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comment',
        ),
    ]
